name: makeup_buddy
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  youtube_player: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - assets/makeup.jpeg
     - assets/shelf.jpg
     - assets/foundation.jpg
     - assets/foundationimg.jpg
     - assets/howtoprimer.jpg
     - assets/mosturizer.jpg
     - assets/samplemosturizers.jpg
     - assets/washface.jpg
     - assets/shadesofconcealors.jpg
     - assets/shadesfoundation.jpg
     - assets/primer.jpg
     - assets/primerimages.jpg
     - assets/concealorss.jpg
     - assets/brushtone.jpg
     - assets/toneskin.jpg
     - assets/colorcorrect.jpg
     - assets/blendfoundat.jpg
     - assets/concealblemish.jpg
     - assets/settingpowder.png
     - assets/finalfoundation.jpg
     - assets/spreadfoundation.jpg
     - assets/smallamount.jpeg
     - assets/faceshapes.jpg
     - assets/eyebrowshapes.jpg
     - assets/howtogromeyebrows.jpg
     - assets/eyebrows.jpg
     - assets/waxing.jpeg
     - assets/filleye.jpeg
     - assets/outline.jpeg
     - assets/tweezers.jpg
     - assets/plucking.jpg
     - assets/shapingkit.jpg
     - assets/acne.jpg
     - assets/manacnes.jpg
     - assets/gyloyc.jpg
     - assets/duduosun.jpg
     - assets/dettoleventone.jpg
     - assets/cetaphil.jpg
     - assets/benzovyl.jpg
     - assets/acnemosturizer.jpg
     - assets/eyebrowfinal.jpg
     - assets/afteracnes.png
     - assets/contour2.jpg
     - assets/contouring.jpg
     - assets/finalcontour.jpg
     - assets/highlighter.jpeg
     - assets/lighterfoundation.jpg
     - assets/darkerfoundation.png
     - assets/blending.JPG
     - assets/lighterfoundation.jpg
     - assets/colorsconcealors.jpg
     - assets/shadesoflipsticks.jpg
     - assets/brightlipsticks.jpg
     - assets/nudelipstickstpe.jpg
     - assets/manyweird.jpg
     - assets/lipstickstypes.jpg
     - assets/redlipsticks.jpg
     - assets/rosepink.jpg
     - assets/taupelipsticks.jpg
     - assets/fuschialipsticks.jpg
     - assets/chocolatebrown.png
     - assets/copperbrown.jpg
     - assets/funnylips.jpg
     - assets/magentalipsticks.jpg
     - assets/nudelipsticks.jpeg
     - assets/bronzelipsticks.jpg
     - assets/peachlipsticks.jpg
     - assets/lipliner.png
     - assets/lipstickguide.jpg
     - assets/darklips.jpeg
     - assets/exfoliatelips.jpg
     - assets/coconutoil2.jpg
     - assets/honeybak.jpg
     - assets/oliveoil.jpg
     - assets/makeupremover.jpg
     - assets/cucumber.jpg
     - assets/lotion.png
     - assets/lipbalm.jpeg
     - assets/mascaratools.jpg
     - assets/metalashcomb.jpg
     - assets/lashserum.jpeg
     - assets/maskarapic.jpg
     - assets/fakeeyelashes.jpg
     - assets/mascara.jpg
     - assets/glitters.jpg  
     - assets/greenshade.jpg
     - assets/glazenails.jpg
     - assets/milkywhite.jpg
     - assets/nails.jpg
     - assets/midnightblue.jpg
     - assets/darkpeach.jpg
     - assets/darkblue.jpg
     - assets/brown.jpg
     - assets/blacknails.jpg
     - assets/3dacrylic.jpg
     - assets/whitenails.jpg
     - assets/yellownails.jpg
     - assets/purple.jpg
     - assets/skyblue.jpg
     - assets/rednails.jpg
     - assets/quiltednails.jpg
     - assets/nailart.jpg
     - assets/nailcollections.jpeg
     - assets/nails2.jpg
     - assets/nailshades.jpg
     - assets/nailshaedds.jpg
     - assets/paleseries.jpg
     - assets/nailgel.jpg
     - assets/nailart.jpg
     - assets/nailstonescrub.jpg
     - assets/nailscrub.jpg
     - assets/nailfile.jpg
     - assets/nailtools.jpg
     - assets/toolss.jpg
     - assets/nailfilebuffer.jpg
     - assets/nailtoolkit.jpg
     - assets/artificialnails.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
